In [1]:
import numpy as np

In [7]:
x = np.array([40,67,57,9.0])
print(x)
print(type(x))
print(x.dtype)

[40. 67. 57.  9.]
<class 'numpy.ndarray'>
float64


In [9]:
x = np.array(["B",67,57,9.0])
print(x)
print(type(x))
print(x.dtype)

['B' '67' '57' '9.0']
<class 'numpy.ndarray'>
<U32


In [13]:
a2 = np.array([[20,40],[60,80]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [60 80]]
<class 'numpy.ndarray'>
(2, 2)


In [21]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [31]:
c = np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [33]:
d = np.array([1.2344,2.34466,4.565656])
np.around(d,2)

array([1.23, 2.34, 4.57])

In [35]:
print(np.sqrt(d))

[1.11103555 1.53122827 2.13673957]


In [39]:
print(np.around(np.sqrt(d),3))

[1.111 1.531 2.137]


In [41]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [45]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [47]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[ 6 15 24]
[12 15 18]


In [53]:
print(np.mean(a2,axis = 1))
print(np.mean(a2,axis = 0))

[2. 5. 8.]
[4. 5. 6.]


In [ ]:
#Matrix Operations

In [61]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.fill_diagonal(a3,0)
a3

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 0]])

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.matmul(a,b)
print(c)

[[19 22]
 [43 50]]


In [66]:
#Transpose

In [68]:
print(a.T)
print(b.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [70]:
a4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
a4[2][2]

9

In [116]:
a4[1:3,0:2]

array([[4, 5],
       [7, 8]])